# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the cm4 branch
  push:
    branches: [ cm4 ]
  pull_request:
    branches: [ cm4 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Environment
      run: |
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev \
          libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs \
          git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils \
          upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf \
          wget curl swig rsync

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Update & Install feeds
        run: |
          ./scripts/feeds update -a && ./scripts/feeds install -a

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          cp defconfig/cm4_defconfig .config
          make defconfig
          make -j8 download
          make -j8 V=s
          
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.board }}
          path: bin/
